spring:
  application:
    name: frcunha-greeting-serice
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
    
greeting-service:
  greeting: "Hola"
  default-value: "Mundo"    
    
